#!/bin/bash
if [ ! -f /config/nginx.conf ]; then
  cp /etc/nginx/nginx.conf /config/nginx.conf
  chown nginx:www-data /config/nginx.conf
fi

if [ ! -d /run/nginx ]; then
  mkdir /run/nginx
fi


if [ -n "${TZ}" ]; then
  zone="/usr/share/zoneinfo/${TZ}"
  if [ -f $zone ]; then
    echo "Setting timezone to ${TZ}"
    cp $zone /etc/localtime
    echo $TZ > /etc/Timezone
  fi
fi

alias ll='ls -lah'
 echo '
 -------------------------------------
 Adjusting UID and GID of nginx
 -------------------------------------'
PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" www-data
usermod -o -u "$PUID" -g "$PGID" nginx

 echo '
 -------------------------------------
 GID/UID
 -------------------------------------'
 echo "
 User uid:    $(id -u nginx)
 User gid:    $(id -g nginx)
 -------------------------------------
 "

chown -R nginx:www-data /etc/nginx
chown -R nginx:www-data /config
chown -R nginx:www-data /run/nginx
chown -R nginx:www-data /var/lib/nginx
